[target.thumbv7em-none-eabihf]
# Flash via OpenOCD + TI ICDI (built-in debugger on Tiva C LaunchPad)
runner = """openocd -f interface/ti-icdi.cfg -f target/tm4c123g.cfg \
            -c "program {bin} verify reset exit" """

[build]
target = "thumbv7em-none-eabihf"
